# Generated by Django 2.2.14 on 2021-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='day',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1),
        ),
    ]
