# Generated by Django 2.2.14 on 2021-03-20 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210320_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='main.Package'),
        ),
    ]
