# Generated by Django 2.2.14 on 2021-03-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210320_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='package',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='package',
            name='day3',
        ),
    ]
